AWSTemplateFormatVersion: '2010-09-09'
Description: Master Stack to deploy CloudBasedProject infrastructure using nested stacks in proper order.

Parameters:
  ProjectName:
    Type: String
    Default: cloudbasedproject

  ImageTag:
    Type: String
    Default: latest

  DatabaseUsername:
    Type: String
    Default: cloudbasedapp

  DatabasePassword:
    Type: String
    NoEcho: true
    Default: cloudbasedapp123



Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://deployment-infras-bucket.s3.eu-west-1.amazonaws.com/VPC.yml
      Parameters:
        ProjectName: !Ref ProjectName


  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds:
        - Fn::ImportValue: !Sub '${ProjectName}-db-subnet-1-id'
        - Fn::ImportValue: !Sub '${ProjectName}-db-subnet-2-id'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-db-subnet-group'

  DatabaseParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: postgres17
      Description: Parameter group for PostgreSQL 17
      Parameters:
        shared_preload_libraries: pg_stat_statements
        log_statement: all
        log_min_duration_statement: 1000
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-db-parameter-group'

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-database'
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '17.5'
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: 20
      StorageType: gp2
      StorageEncrypted: true
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      DBParameterGroupName: !Ref DatabaseParameterGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub '${ProjectName}-db-sg-id'
      BackupRetentionPeriod: 7
      PreferredBackupWindow: '03:00-04:00'
      PreferredMaintenanceWindow: 'sun:04:00-sun:05:00'
      MultiAZ: false
      AutoMinorVersionUpgrade: true
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-database'

  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: cloudbasedproject-db-credential
      Description: Database credentials for Cloud Based Project
      SecretString: !Sub |
        {
          "username": "${DatabaseUsername}",
          "password": "${DatabasePassword}",
          "host": "${DatabaseInstance.Endpoint.Address}",
          "port": "5432",
          "dbname": "postgres"
        }
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-db-credential'


  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://deployment-infras-bucket.s3.eu-west-1.amazonaws.com/ECS.yml
      Parameters:
        ProjectName: !Ref ProjectName
        ImageTag: !Ref ImageTag

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECSStack
    Properties:
      TemplateURL: https://deployment-infras-bucket.s3.eu-west-1.amazonaws.com/BG-Tranform.yml
      Parameters:
        ProjectName: !Ref ProjectName
